CREATE TABLE IF NOT EXISTS Meals(
    id SERIAL PRIMARY KEY,
    meal_type VARCHAR(50),
    Vendor_id INT,
    is_optional BOOlEAN TRUE,
    CONSTRAINT fk_meal_vendor FOREIGN KEY (Vendor_id) REFERENCES Vendors(id)
);
INSERT INTO Meals (meal_type, Vendor_id, is_optional)
VALUES
('South Indian Breakfast',2,FALSE),
('North Indian Breakfast',2,FALSE),
('Veg Lunch',2,FALSE),
('Veg Dinner',2,FALSE),
('Kids Breakfast',2,TRUE),
('Continental Breakfast',6,TRUE),
('Kids Meal Combo',6,TRUE),
('Light Lunch',6,TRUE),
('Healthy Dinner',6,TRUE),
('Lunch Buffet',10,FALSE),
('Dinner Buffet',10,FALSE),
('Executive Lunch',10,FALSE),
('Veg Combo Meal',10,FALSE),
('Mini Meals',10,TRUE),
('Organic Veg Lunch',14,FALSE),
('Jain Meal',14,TRUE),
('Ayurvedic Lunch',14,TRUE),
('Millet Dinner',14,TRUE),
('South Indian Thali',18,FALSE),
('North Indian Thali',18,FALSE),
('Mini Tiffin',18,TRUE),
('Evening Snacks',18,TRUE),
('Royal Veg Feast',22,FALSE),
('Premium Dinner',22,FALSE),
('Family Meal Combo',22,TRUE),
('Special Occasion Meal',22,TRUE),
('Indian Lunch Combo',26,FALSE),
('Dinner Set Meal',26,FALSE),
('Festival Special Meal',26,TRUE),
('Kids Lunch Box',26,TRUE),
('Spicy Veg Lunch',30,FALSE),
('Non-Spicy Veg Dinner',30,TRUE),
('Street Food Platter',30,TRUE),
('Evening Chaat',30,TRUE),
('Healthy Diet Meal',34,TRUE),
('Low Calorie Lunch',34,TRUE),
('Ayurvedic Dinner',34,TRUE),
('Organic Breakfast',34,TRUE),
('International Lunch',38,FALSE),
('Western Dinner',38,TRUE),
('Italian Veg Meal',38,TRUE),
('Mexican Veg Bowl',38,TRUE),
('Family Dinner Combo',42,FALSE),
('Kids Veg Meal',42,TRUE),
('Lunch Special',42,FALSE),
('Dinner Special',42,FALSE),
('Tandoori Lunch',46,FALSE),
('Tandoori Dinner',46,FALSE),
('Grilled Veg Platter',46,TRUE),
('BBQ Veg Meal',46,TRUE),
('South Indian Dinner',50,FALSE),
('North Indian Dinner',50,FALSE),
('Light Dinner',50,TRUE),
('Senior Citizen Meal',50,TRUE);
